apiVersion: acme.com/v1
kind: Topic
metadata:
  name: my-topic

topicName: eladb-topic-1234

---
apiVersion: acme.com/v1
kind: Run
metadata:
  name: check-topic
command:
  - /bin/sh
  - -c
  - echo "hello, ${ref://topics.acme.com/my-topic/topicArn}"
